### ISSUE TITLE
colmap fails to build with CGAL 5.0.1

### ISSUE THREAD

**Issue by jasjuang** [colmap/colmap#793]
**Describe the bug**
colmap fails to build with CGAL 5.0.1

**To Reproduce**
```
git clone https://github.com/colmap/colmap
cd colmap && mkdir build && cd build
cmake -DBOOST_STATIC=OFF ..
make
```

Error message:
```
[ 54%] Building CXX object src/CMakeFiles/colmap.dir/mvs/meshing.cc.o
In file included from /usr/include/CGAL/Triangulation_data_structure_3.h:35:0,
                 from /usr/include/CGAL/Triangulation_3.h:39,
                 from /usr/include/CGAL/Delaunay_triangulation_3.h:25,
                 from /home/jasjuang/colmap/src/mvs/meshing.cc:39:
/usr/include/CGAL/iterator.h:663:16: error: ‘decay_t’ in namespace ‘std’ does not name a template type
   typedef std::decay_t<typename cpp11::result_of<Op(arg_type)>::type> value_type;
                ^~~~~~~
/usr/include/CGAL/iterator.h:665:11: error: ‘value_type’ does not name a type; did you mean ‘arg_type’?
   typedef value_type const*                                     pointer;
           ^~~~~~~~~~
           arg_type
/usr/include/CGAL/iterator.h:666:11: error: ‘value_type’ does not name a type; did you mean ‘arg_type’?
   typedef value_type const&                                     reference;
           ^~~~~~~~~~
           arg_type
/usr/include/CGAL/iterator.h:671:11: error: ‘value_type’ does not name a type; did you mean ‘arg_type’?
   mutable value_type val;  // Note: mutable is needed because we want to
           ^~~~~~~~~~
           arg_type
/usr/include/CGAL/iterator.h:699:9: error: ‘value_type’ does not name a type; did you mean ‘arg_type’?
   const value_type& operator*() const {
         ^~~~~~~~~~
         arg_type
/usr/include/CGAL/iterator.h:715:9: error: ‘value_type’ does not name a type; did you mean ‘arg_type’?
   const value_type& operator[](difference_type i) const {
         ^~~~~~~~~~
         arg_type
/usr/include/CGAL/iterator.h:1321:44: error: ‘std::index_sequence’ has not been declared
 auto to_tuple(std::tuple<Args...> &t, std::index_sequence<Is...>)
                                            ^~~~~~~~~~~~~~
/usr/include/CGAL/iterator.h:1321:58: error: expected ‘,’ or ‘...’ before ‘<’ token
 auto to_tuple(std::tuple<Args...> &t, std::index_sequence<Is...>)
                                                          ^
/usr/include/CGAL/iterator.h:1321:65: error: ‘to_tuple’ function uses ‘auto’ type specifier without trailing return type
 auto to_tuple(std::tuple<Args...> &t, std::index_sequence<Is...>)
                                                                 ^
/usr/include/CGAL/iterator.h:1321:65: note: deduced return type only available with -std=c++14 or -std=gnu++14
/usr/include/CGAL/iterator.h: In member function ‘CGAL::Dispatch_output_iterator<std::tuple<_Tps ...>, std::tuple<_Elements ...> >::operator std::tuple<O& ...>()’:
/usr/include/CGAL/iterator.h:1414:49: error: ‘index_sequence_for’ is not a member of ‘std’
     return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                                 ^~~~~~~~~~~~~~~~~~
/usr/include/CGAL/iterator.h:1414:69: error: expected primary-expression before ‘...’ token
     return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                                                     ^~~
/usr/include/CGAL/iterator.h: In member function ‘CGAL::Dispatch_output_iterator<std::tuple<_Tps ...>, std::tuple<_Elements ...> >::operator std::tuple<const O& ...>() const’:
/usr/include/CGAL/iterator.h:1419:49: error: ‘index_sequence_for’ is not a member of ‘std’
     return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                                 ^~~~~~~~~~~~~~~~~~
/usr/include/CGAL/iterator.h:1419:69: error: expected primary-expression before ‘...’ token
     return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                                                     ^~~
In file included from /usr/include/CGAL/Kernel/global_functions.h:25:0,
                 from /usr/include/CGAL/Cartesian/Cartesian_base.h:22,
                 from /usr/include/CGAL/Simple_cartesian.h:20,
                 from /usr/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20,
                 from /home/jasjuang/colmap/src/mvs/meshing.cc:40:
/usr/include/CGAL/Kernel/hash_functions.h: At global scope:
/usr/include/CGAL/Kernel/hash_functions.h:25:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:47:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:57:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:66:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:75:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:84:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:93:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:102:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:126:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:135:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:145:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:154:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:164:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
/usr/include/CGAL/Kernel/hash_functions.h:174:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
             ^~~~~~~~~~~
In file included from /usr/include/CGAL/Lazy_exact_nt.h:33:0,
                 from /usr/include/CGAL/internal/Exact_type_selector.h:25,
                 from /usr/include/CGAL/Exact_kernel_selector.h:26,
                 from /usr/include/CGAL/Filtered_kernel.h:22,
                 from /usr/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:21,
                 from /home/jasjuang/colmap/src/mvs/meshing.cc:40:
/usr/include/CGAL/Lazy.h:108:30: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 template<class T>inline std::enable_if_t<std::is_arithmetic<T>::value||std::is_enum<T>::value, T> approx(T d){return d;}
                              ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:109:30: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 template<class T>inline std::enable_if_t<std::is_arithmetic<T>::value||std::is_enum<T>::value, T> exact (T d){return d;}
                              ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:110:30: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 template<class T>inline std::enable_if_t<std::is_arithmetic<T>::value||std::is_enum<T>::value, unsigned> depth(T){return 0;}
                              ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:113:30: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 template<class T>inline std::enable_if_t<std::is_empty<T>::value, T> exact(T){return {};}
                              ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:114:30: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 template<class T>inline std::enable_if_t<std::is_empty<T>::value, T> approx(T){return {};}
                              ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:115:30: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 template<class T>inline std::enable_if_t<std::is_empty<T>::value, unsigned> depth(T){return 0;}
                              ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:118:31: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 template <class T, class=std::enable_if_t<is_iterator_type<T,std::input_iterator_tag>::value>>
                               ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:118:42: error: expected ‘>’ before ‘<’ token
 template <class T, class=std::enable_if_t<is_iterator_type<T,std::input_iterator_tag>::value>>
                                          ^
/usr/include/CGAL/Lazy.h:119:22: error: ‘exact’ function uses ‘auto’ type specifier without trailing return type
 auto exact(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::exact(u);});}
                      ^
/usr/include/CGAL/Lazy.h:119:22: note: deduced return type only available with -std=c++14 or -std=gnu++14
/usr/include/CGAL/Lazy.h: In function ‘auto CGAL::exact(const T&)’:
/usr/include/CGAL/Lazy.h:119:64: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
 auto exact(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::exact(u);});}
                                                                ^~~~
/usr/include/CGAL/Lazy.h: In lambda function:
/usr/include/CGAL/Lazy.h:119:98: error: no matching function for call to ‘exact(const int&)’
 auto exact(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::exact(u);});}
                                                                                                  ^
/usr/include/CGAL/Lazy.h:84:1: note: candidate: template<class AT, class ET, class E2A> const ET& CGAL::exact(const CGAL::Lazy<AT, ET, E2A>&)
 exact(const Lazy<AT,ET,E2A>& l)
 ^~~~~
/usr/include/CGAL/Lazy.h:84:1: note:   template argument deduction/substitution failed:
/usr/include/CGAL/Lazy.h:119:98: note:   mismatched types ‘const CGAL::Lazy<AT, ET, E2A>’ and ‘const int’
 auto exact(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::exact(u);});}
                                                                                                  ^
/usr/include/CGAL/Lazy.h:104:1: note: candidate: const CGAL::Bbox_2& CGAL::exact(const CGAL::Bbox_2&)
 CGAL_LAZY_FORWARD(Bbox_2)
 ^
/usr/include/CGAL/Lazy.h:104:1: note:   no known conversion for argument 1 from ‘const int’ to ‘const CGAL::Bbox_2&’
/usr/include/CGAL/Lazy.h:105:1: note: candidate: const CGAL::Bbox_3& CGAL::exact(const CGAL::Bbox_3&)
 CGAL_LAZY_FORWARD(Bbox_3)
 ^
/usr/include/CGAL/Lazy.h:105:1: note:   no known conversion for argument 1 from ‘const int’ to ‘const CGAL::Bbox_3&’
/usr/include/CGAL/Lazy.h:119:6: note: candidate: template<class T, class> auto CGAL::exact(const T&)
 auto exact(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::exact(u);});}
      ^~~~~
/usr/include/CGAL/Lazy.h:119:6: note:   template argument deduction/substitution failed:
/usr/include/CGAL/Lazy.h: At global scope:
/usr/include/CGAL/Lazy.h:120:31: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 template <class T, class=std::enable_if_t<is_iterator_type<T,std::input_iterator_tag>::value>>
                               ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:120:42: error: expected ‘>’ before ‘<’ token
 template <class T, class=std::enable_if_t<is_iterator_type<T,std::input_iterator_tag>::value>>
                                          ^
/usr/include/CGAL/Lazy.h:121:23: error: ‘approx’ function uses ‘auto’ type specifier without trailing return type
 auto approx(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::approx(u);});}
                       ^
/usr/include/CGAL/Lazy.h:121:23: note: deduced return type only available with -std=c++14 or -std=gnu++14
/usr/include/CGAL/Lazy.h: In function ‘auto CGAL::approx(const T&)’:
/usr/include/CGAL/Lazy.h:121:65: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
 auto approx(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::approx(u);});}
                                                                 ^~~~
/usr/include/CGAL/Lazy.h: In lambda function:
/usr/include/CGAL/Lazy.h:121:100: error: no matching function for call to ‘approx(const int&)’
 auto approx(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::approx(u);});}
                                                                                                    ^
/usr/include/CGAL/Lazy.h:66:1: note: candidate: template<class AT, class ET, class E2A> const AT& CGAL::approx(const CGAL::Lazy<AT, ET, E2A>&)
 approx(const Lazy<AT,ET,E2A>& l)
 ^~~~~~
/usr/include/CGAL/Lazy.h:66:1: note:   template argument deduction/substitution failed:
/usr/include/CGAL/Lazy.h:121:100: note:   mismatched types ‘const CGAL::Lazy<AT, ET, E2A>’ and ‘const int’
 auto approx(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::approx(u);});}
                                                                                                    ^
/usr/include/CGAL/Lazy.h:75:1: note: candidate: template<class AT, class ET, class E2A> AT& CGAL::approx(CGAL::Lazy<AT, ET, E2A>&)
 approx(Lazy<AT,ET,E2A>& l)
 ^~~~~~
/usr/include/CGAL/Lazy.h:75:1: note:   template argument deduction/substitution failed:
/usr/include/CGAL/Lazy.h:121:100: note:   mismatched types ‘CGAL::Lazy<AT, ET, E2A>’ and ‘const int’
 auto approx(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::approx(u);});}
                                                                                                    ^
/usr/include/CGAL/Lazy.h:104:1: note: candidate: const CGAL::Bbox_2& CGAL::approx(const CGAL::Bbox_2&)
 CGAL_LAZY_FORWARD(Bbox_2)
 ^
/usr/include/CGAL/Lazy.h:104:1: note:   no known conversion for argument 1 from ‘const int’ to ‘const CGAL::Bbox_2&’
/usr/include/CGAL/Lazy.h:105:1: note: candidate: const CGAL::Bbox_3& CGAL::approx(const CGAL::Bbox_3&)
 CGAL_LAZY_FORWARD(Bbox_3)
 ^
/usr/include/CGAL/Lazy.h:105:1: note:   no known conversion for argument 1 from ‘const int’ to ‘const CGAL::Bbox_3&’
/usr/include/CGAL/Lazy.h:121:6: note: candidate: template<class T, class> auto CGAL::approx(const T&)
 auto approx(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::approx(u);});}
      ^~~~~~
/usr/include/CGAL/Lazy.h:121:6: note:   template argument deduction/substitution failed:
/usr/include/CGAL/Lazy.h: At global scope:
/usr/include/CGAL/Lazy.h:122:31: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 template <class T, class=std::enable_if_t<is_iterator_type<T,std::input_iterator_tag>::value>>
                               ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:122:42: error: expected ‘>’ before ‘<’ token
 template <class T, class=std::enable_if_t<is_iterator_type<T,std::input_iterator_tag>::value>>
                                          ^
In file included from /usr/include/CGAL/Lazy_exact_nt.h:33:0,
                 from /usr/include/CGAL/internal/Exact_type_selector.h:25,
                 from /usr/include/CGAL/Exact_kernel_selector.h:26,
                 from /usr/include/CGAL/Filtered_kernel.h:22,
                 from /usr/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:21,
                 from /home/jasjuang/colmap/src/mvs/meshing.cc:40:
/usr/include/CGAL/Lazy.h:320:33: error: ‘std::index_sequence’ has not been declared
   void update_exact_helper(std::index_sequence<I...>) const {
                                 ^~~~~~~~~~~~~~
/usr/include/CGAL/Lazy.h:320:47: error: expected ‘,’ or ‘...’ before ‘<’ token
   void update_exact_helper(std::index_sequence<I...>) const {
                                               ^
/usr/include/CGAL/Lazy.h: In member function ‘void CGAL::Lazy_rep_n<AT, ET, AC, EC, E2A, L>::update_exact() const’:
/usr/include/CGAL/Lazy.h:327:30: error: ‘make_index_sequence’ is not a member of ‘std’
     update_exact_helper(std::make_index_sequence<sizeof...(L)>{});
                              ^~~~~~~~~~~~~~~~~~~
/usr/include/CGAL/Lazy.h:327:30: note: suggested alternative:
In file included from /usr/include/boost/fusion/container/vector/vector.hpp:28:0,
                 from /usr/include/boost/fusion/container/vector/vector10.hpp:25,
                 from /usr/include/boost/fusion/view/transform_view/transform_view.hpp:22,
                 from /usr/include/boost/fusion/algorithm/transformation/transform.hpp:11,
                 from /usr/include/boost/iterator/zip_iterator.hpp:31,
                 from /usr/include/CGAL/Triangulation_3.h:66,
                 from /usr/include/CGAL/Delaunay_triangulation_3.h:25,
                 from /home/jasjuang/colmap/src/mvs/meshing.cc:39:
/usr/include/boost/fusion/support/detail/index_sequence.hpp:59:12: note:   ‘boost::fusion::detail::make_index_sequence’
     struct make_index_sequence
            ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/CGAL/Lazy_exact_nt.h:33:0,
                 from /usr/include/CGAL/internal/Exact_type_selector.h:25,
                 from /usr/include/CGAL/Exact_kernel_selector.h:26,
                 from /usr/include/CGAL/Filtered_kernel.h:22,
                 from /usr/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:21,
                 from /home/jasjuang/colmap/src/mvs/meshing.cc:40:
/usr/include/CGAL/Lazy.h:327:63: error: expected primary-expression before ‘{’ token
     update_exact_helper(std::make_index_sequence<sizeof...(L)>{});
                                                               ^
/usr/include/CGAL/Lazy.h: At global scope:
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:39: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:39: note: suggested alternative: ‘remove_reference’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
                                       remove_reference
/usr/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^~
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:39: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:39: note: suggested alternative: ‘remove_reference’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
                                       remove_reference
/usr/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^~
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:39: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:39: note: suggested alternative: ‘remove_reference’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
                                       remove_reference
/usr/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^~
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:39: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:39: note: suggested alternative: ‘remove_reference’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
                                       remove_reference
/usr/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^~
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:22: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/include/CGAL/Lazy.h:831:22: note: suggested alternative: ‘remove_cv’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                      ^~~~~~~~~~~
                      remove_cv
/usr/include/CGAL/Lazy.h:831:39: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:39: note: suggested alternative: ‘remove_reference’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                       ^~~~~~~~~~~~~~~~~~
                                       remove_reference
/usr/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^~
/usr/include/CGAL/Lazy.h:831:3: error: invalid use of template-name ‘CGAL::Lazy_exact_nt’ without an argument list
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
   ^~~~~~~~~~~~~
/usr/include/CGAL/Lazy.h:831:3: note: class template argument deduction is only available with -std=c++1z or -std=gnu++1z
In file included from /usr/include/CGAL/Triangulation_3.h:70:0,
                 from /usr/include/CGAL/Delaunay_triangulation_3.h:25,
                 from /home/jasjuang/colmap/src/mvs/meshing.cc:39:
/usr/include/CGAL/internal/Static_filters/tools.h:23:7: note: ‘template<class ET> class CGAL::Lazy_exact_nt’ declared here
 class Lazy_exact_nt;
       ^~~~~~~~~~~~~
In file included from /usr/include/CGAL/Lazy_exact_nt.h:33:0,
                 from /usr/include/CGAL/internal/Exact_type_selector.h:25,
                 from /usr/include/CGAL/Exact_kernel_selector.h:26,
                 from /usr/include/CGAL/Filtered_kernel.h:22,
                 from /usr/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:21,
                 from /home/jasjuang/colmap/src/mvs/meshing.cc:40:
/usr/include/CGAL/Lazy.h:831:16: error: expected initializer before ‘<’ token
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                ^
src/CMakeFiles/colmap.dir/build.make:810: recipe for target 'src/CMakeFiles/colmap.dir/mvs/meshing.cc.o' failed
make[2]: *** [src/CMakeFiles/colmap.dir/mvs/meshing.cc.o] Error 1
CMakeFiles/Makefile2:838: recipe for target 'src/CMakeFiles/colmap.dir/all' failed
make[1]: *** [src/CMakeFiles/colmap.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Expected behavior**
colmap should be able to compile with the latest CGAL release

**Desktop:**
 - OS: Ubuntu 18.04
 - Compiler: GCC 7

**Comment by jasjuang** [comment]
After looking carefully at the error message, this can be solved by adding `set(CMAKE_CXX_STANDARD 14)` on top of the CMakeLists.

**Comment by noahstier** [comment]
I added that line and then got this error:

```
error: unable to find numeric literal operator ‘operator""Q’
             BOOST_MATH_BIG_CONSTANT(T, 113, 0.00118142849742309772151454518093813615),                  
             ^       
```
which I fixed by adding
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DBOOST_MATH_DISABLE_FLOAT128")`
