### ISSUE TITLE
Linker error on Ubuntu 18.04 [-lGL instead of -lOpenGL?]

### ISSUE THREAD

**Issue by snavely** [colmap/colmap#1271]
**Describe the bug**
I am filing this bug partly in case I or someone else runs into this problem again... On an AWS Deep Learning instance, I was unable to compile COLMAP with the default settings. I get the following linker error, which I was able to fix manually as noted below:

```
[ 95%] Linking CXX executable colmap                                             [647/1907]
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libOpenGL.so: undefined reference
 to `_glapi_tls_Current'                                                                   
collect2: error: ld returned 1 exit status                                                 
src/exe/CMakeFiles/colmap_exe.dir/build.make:264: recipe for target 'src/exe/colmap' failedmake[2]: *** [src/exe/colmap] Error 1                                                      
CMakeFiles/Makefile2:784: recipe for target 'src/exe/CMakeFiles/colmap_exe.dir/all' failed 
make[1]: *** [src/exe/CMakeFiles/colmap_exe.dir/all] Error 2                               Makefile:135: recipe for target 'all' failed                                               
make: *** [all] Error 2                                                                    
```

To fix this problem, I manually edited the file src/exe/CMakeFiles/colmap_exe.dir/link.txt and changed -lOpenGL to -lGL. Then things worked. I don't know if that is the right fix (simply removing -lOpenGL led to other errors), but it did the trick. I don't know what the underlying issue is, e.g., whether with cmake, the cmake config files, or with something else.

**To Reproduce**
1. Launch an AWS Deep Learning instance running Ubuntu 18.04.
2. Try to install and build COLMAP. (I ran "cmake .. -DGUI_ENABLED=OFF")

**Expected behavior**
COLMAP compiles successfully.

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu 18.04.5 LTS, AWS Deep Learning AMI on a p3.2xlarge instance

**Comment by alvinwan** [comment]
Huh, odd. This worked for me too. For posterity, I *also* had to follow #713. In particular, make the `.so` files discoverable again:
```
sudo apt-install --reinstall --yes mesa-common-dev
```
Then per  @yyakupoglu 's recommendation, I noticed a bunch of my openGL-related symlinks were broken (for me, `libGL.so`, `libGLX.so` and `libGLdispatch.so` were all broken)
```
find /usr/lib/x86_64-linux-gnu/ -xtype l
```
For example, here's how I fixed my `libGL.so`
```
sudo rm libGL.so
sudo ln -s `find /usr/lib/x86_64-linux-gnu/ -type f | grep libGL.so` /usr/lib/x86_64-linux-gnu/libGL.so
```
After all that, I had to use @snavely 's hack changing `lOpenGL` to `lGL`. Not sure why that worked either 🤷🏻‍♂️

**Comment by yuguangxie** [comment]
The above method doesn't work for me. I try to build colmap in colab, but the link error "undefined reference to '_glapi_tls_Current'" happened. I found a solution by installing "libglvnd". The following command is what I used:
```
git clone https://github.com/NVIDIA/libglvnd 
sudo apt-get install libxext-dev libx11-dev x11proto-gl-dev
cd libglvnd/
sudo apt-get install autoconf automake libtool
sudo apt-get install libffi-dev
./autogen.sh
./configure
make  -j4
sudo make install
```
When I cmake the colmap again, I found the path of OpenGL is changed to "/usr/local/lib/libOpenGL.so "(before libglvnd is in "usr/lib/x86_64-linux-gnu/libOpenGL.so"). After that, I make the project successfully.
I'm not sure what's going on in libOpenGL, since I'm not an expert in this.

Best wishes!

**Comment by tblanchard** [comment]
Thank YOU!

Been banging my head on this for days.  Moving forward.

**Comment by senyangjiang** [comment]
> The above method doesn't work for me. I try to build colmap in colab, but the link error "undefined reference to '_glapi_tls_Current'" happened. I found a solution by installing "libglvnd". The following command is what I used:
> 
> ```
> git clone https://github.com/NVIDIA/libglvnd 
> sudo apt-get install libxext-dev libx11-dev x11proto-gl-dev
> cd libglvnd/
> sudo apt-get install autoconf automake libtool
> sudo apt-get install libffi-dev
> ./autogen.sh
> ./configure
> make  -j4
> sudo make install
> ```
> 
> When I cmake the colmap again, I found the path of OpenGL is changed to "/usr/local/lib/libOpenGL.so "(before libglvnd is in "usr/lib/x86_64-linux-gnu/libOpenGL.so"). After that, I make the project successfully. I'm not sure what's going on in libOpenGL, since I'm not an expert in this.
> 
> Best wishes!

You are my lifesaver! This solution works on my ec2 instance with Ubuntu 20.04.

**Comment by raja-kumar** [comment]
> The above method doesn't work for me. I try to build colmap in colab, but the link error "undefined reference to '_glapi_tls_Current'" happened. I found a solution by installing "libglvnd". The following command is what I used:
> 
> ```
> git clone https://github.com/NVIDIA/libglvnd 
> sudo apt-get install libxext-dev libx11-dev x11proto-gl-dev
> cd libglvnd/
> sudo apt-get install autoconf automake libtool
> sudo apt-get install libffi-dev
> ./autogen.sh
> ./configure
> make  -j4
> sudo make install
> ```
> 
> When I cmake the colmap again, I found the path of OpenGL is changed to "/usr/local/lib/libOpenGL.so "(before libglvnd is in "usr/lib/x86_64-linux-gnu/libOpenGL.so"). After that, I make the project successfully. I'm not sure what's going on in libOpenGL, since I'm not an expert in this.
> 
> Best wishes!

_/\_ I have been struggling for the whole day with this. Finally, this worked. Thanks!

**Comment by fantasy-fish** [comment]
Can't find this directory `src/exe/CMakeFiles/colmap_exe.dir/link.txt`

**Comment by gigit0000** [comment]
> The above method doesn't work for me. I try to build colmap in colab, but the link error "undefined reference to '_glapi_tls_Current'" happened. I found a solution by installing "libglvnd". The following command is what I used:
> 
> ```
> git clone https://github.com/NVIDIA/libglvnd 
> sudo apt-get install libxext-dev libx11-dev x11proto-gl-dev
> cd libglvnd/
> sudo apt-get install autoconf automake libtool
> sudo apt-get install libffi-dev
> ./autogen.sh
> ./configure
> make  -j4
> sudo make install
> ```
> 
> When I cmake the colmap again, I found the path of OpenGL is changed to "/usr/local/lib/libOpenGL.so "(before libglvnd is in "usr/lib/x86_64-linux-gnu/libOpenGL.so"). After that, I make the project successfully. I'm not sure what's going on in libOpenGL, since I'm not an expert in this.
> 
> Best wishes!

Confirms it still works.

**Comment by Hokage-7th** [comment]
> The above method doesn't work for me. I try to build colmap in colab, but the link error "undefined reference to '_glapi_tls_Current'" happened. I found a solution by installing "libglvnd". The following command is what I used:
> 
> ```
> git clone https://github.com/NVIDIA/libglvnd 
> sudo apt-get install libxext-dev libx11-dev x11proto-gl-dev
> cd libglvnd/
> sudo apt-get install autoconf automake libtool
> sudo apt-get install libffi-dev
> ./autogen.sh
> ./configure
> make  -j4
> sudo make install
> ```
> 
> When I cmake the colmap again, I found the path of OpenGL is changed to "/usr/local/lib/libOpenGL.so "(before libglvnd is in "usr/lib/x86_64-linux-gnu/libOpenGL.so"). After that, I make the project successfully. I'm not sure what's going on in libOpenGL, since I'm not an expert in this.
> 
> Best wishes!

Thank you!How did you find the solution,amazing!
