### ISSUE TITLE
Issues building on Kubuntu 17.10

### ISSUE THREAD

**Issue by Talkless** [colmap/colmap#377]
Hi,

I'm struggling to build colmap for my fried on Kubuntu 17.10.

First of all, NVIDIA CUDA SDK 9.2 does not support GCC >5? Though they provide "Ubuntu 17.10" package [0], meanwhile building with stock GCC 7.2.0 fails with `unsupported GNU version! gcc versions later than 5 are not supported`.

OK, so I've installed GCC 4.9 [1], recompiled `ceres-solver` with same compiler using `-DCMAKE_CXX_COMPILER=/usr/bin/g++-4.9 -DCMAKE_C_COMPILER=/usr/bin/gcc-4.9`, but while building (actually linking) `colmap` now I get link errors:

```
[  0%] Automatic RCC for target flann
[  0%] Built target flann_autogen
[  1%] Built target flann
[  1%] Automatic RCC for target graclus
[  1%] Built target graclus_autogen
[ 23%] Built target graclus
[ 25%] Automatic RCC for target lsd
[ 25%] Built target lsd_autogen
[ 25%] Built target lsd
[ 25%] Automatic RCC for target pba
[ 25%] Built target pba_autogen
[ 27%] Built target pba
[ 27%] Automatic RCC for target poisson_recon
[ 27%] Built target poisson_recon_autogen
[ 31%] Built target poisson_recon
[ 31%] Automatic RCC for target sift_gpu
[ 31%] Built target sift_gpu_autogen
[ 37%] Built target sift_gpu
[ 37%] Automatic RCC for target sqlite3
[ 37%] Built target sqlite3_autogen
[ 37%] Built target sqlite3
[ 39%] Automatic RCC for target vlfeat
[ 39%] Built target vlfeat_autogen
[ 52%] Built target vlfeat
[ 52%] Automatic RCC for target colmap_cuda
[ 52%] Built target colmap_cuda_autogen
[ 54%] Built target colmap_cuda
[ 56%] Automatic RCC for target colmap
[ 56%] Built target colmap_autogen
[ 98%] Built target colmap
[ 98%] Automatic RCC for target colmap_exe
[ 98%] Built target colmap_exe_autogen
[100%] Linking CXX executable colmap
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `boost::program_options::typed_value<std::string, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
colmap.cc:(.text._ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x19): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `boost::program_options::typed_value<bool, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
colmap.cc:(.text._ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x19): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool*, int)'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int)':
colmap.cc:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKSsS4_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKSsS4_i]+0x36): undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
colmap.cc:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKSsS4_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKSsS4_i]+0x4c): undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::string const&, int)'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `std::string* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
colmap.cc:(.text._ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `std::string* google::MakeCheckOpString<unsigned int, unsigned int>(unsigned int const&, unsigned int const&, char const*)':
colmap.cc:(.text._ZN6google17MakeCheckOpStringIjjEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIjjEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `std::string* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
colmap.cc:(.text._ZN6google17MakeCheckOpStringImmEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringImmEEPSsRKT_RKT0_PKc]+0x51): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `std::string* google::MakeCheckOpString<unsigned long, int>(unsigned long const&, int const&, char const*)':
colmap.cc:(.text._ZN6google17MakeCheckOpStringImiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringImiEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `std::string* google::MakeCheckOpString<int, unsigned long>(int const&, unsigned long const&, char const*)':
colmap.cc:(.text._ZN6google17MakeCheckOpStringIimEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIimEEPSsRKT_RKT0_PKc]+0x51): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
CMakeFiles/colmap_exe.dir/colmap.cc.o:colmap.cc:(.text._ZN6google17MakeCheckOpStringIlmEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIlmEEPSsRKT_RKT0_PKc]+0x51): more undefined references to `google::base::CheckOpMessageBuilder::NewString()' follow
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `boost::program_options::typed_value<std::string, char>::name() const':
colmap.cc:(.text._ZNK5boost15program_options11typed_valueISscE4nameEv[_ZNK5boost15program_options11typed_valueISscE4nameEv]+0x35): undefined reference to `boost::program_options::arg'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `boost::program_options::typed_value<bool, char>::name() const':
colmap.cc:(.text._ZNK5boost15program_options11typed_valueIbcE4nameEv[_ZNK5boost15program_options11typed_valueIbcE4nameEv]+0x35): undefined reference to `boost::program_options::arg'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `boost::program_options::typed_value<int, char>::name() const':
colmap.cc:(.text._ZNK5boost15program_options11typed_valueIicE4nameEv[_ZNK5boost15program_options11typed_valueIicE4nameEv]+0x35): undefined reference to `boost::program_options::arg'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `boost::program_options::typed_value<double, char>::name() const':
colmap.cc:(.text._ZNK5boost15program_options11typed_valueIdcE4nameEv[_ZNK5boost15program_options11typed_valueIdcE4nameEv]+0x35): undefined reference to `boost::program_options::arg'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `void boost::program_options::validate<int, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long)':
colmap.cc:(.text._ZN5boost15program_options8validateIicEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l[_ZN5boost15program_options8validateIicEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l]+0x671): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
CMakeFiles/colmap_exe.dir/colmap.cc.o: In function `void boost::program_options::validate<double, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, double*, long)':
colmap.cc:(.text._ZN5boost15program_options8validateIdcEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l[_ZN5boost15program_options8validateIdcEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l]+0x417): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): more undefined references to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const' follow
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueISscEE[_ZTVN5boost15program_options11typed_valueISscEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueIbcEE[_ZTVN5boost15program_options11typed_valueIbcEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueIicEE[_ZTVN5boost15program_options11typed_valueIicEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
CMakeFiles/colmap_exe.dir/colmap.cc.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueIdcEE[_ZTVN5boost15program_options11typed_valueIdcEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../libcolmap.a(database.cc.o): In function `std::string* google::MakeCheckOpString<unsigned int, int>(unsigned int const&, int const&, char const*)':
database.cc:(.text._ZN6google17MakeCheckOpStringIjiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIjiEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../libcolmap.a(database.cc.o): In function `std::string* google::MakeCheckOpString<unsigned int, unsigned long>(unsigned int const&, unsigned long const&, char const*)':
database.cc:(.text._ZN6google17MakeCheckOpStringIjmEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIjmEEPSsRKT_RKT0_PKc]+0x51): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../libcolmap.a(pose.cc.o): In function `std::string* google::MakeCheckOpString<double, int>(double const&, int const&, char const*)':
pose.cc:(.text._ZN6google17MakeCheckOpStringIdiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIdiEEPSsRKT_RKT0_PKc]+0x52): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../libcolmap.a(reconstruction.cc.o): In function `std::string* google::MakeCheckOpString<std::string, std::string>(std::string const&, std::string const&, char const*)':
reconstruction.cc:(.text._ZN6google17MakeCheckOpStringISsSsEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringISsSsEEPSsRKT_RKT0_PKc]+0x59): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../libcolmap.a(reconstruction.cc.o): In function `std::string* google::MakeCheckOpString<double, double>(double const&, double const&, char const*)':
reconstruction.cc:(.text._ZN6google17MakeCheckOpStringIddEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIddEEPSsRKT_RKT0_PKc]+0x54): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../libcolmap.a(warp.cc.o):warp.cc:(.text._ZN6google17MakeCheckOpStringIbbEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIbbEEPSsRKT_RKT0_PKc]+0x52): more undefined references to `google::base::CheckOpMessageBuilder::NewString()' follow
../libcolmap.a(bundle_adjustment.cc.o): In function `colmap::BundleAdjuster::Solve(colmap::Reconstruction*)':
bundle_adjustment.cc:(.text+0x6ace): undefined reference to `ceres::Solver::Options::IsValid(std::string*) const'
../libcolmap.a(bundle_adjustment.cc.o): In function `colmap::RigBundleAdjuster::Solve(colmap::Reconstruction*, std::vector<colmap::CameraRig, std::allocator<colmap::CameraRig> >*)':
bundle_adjustment.cc:(.text+0x8653): undefined reference to `ceres::Solver::Options::IsValid(std::string*) const'
../libcolmap.a(bitmap.cc.o): In function `char const* boost::re_detail_106200::re_is_set_member<char const*, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(char const*, char const*, boost::re_detail_106200::re_set_long<unsigned int> const*, boost::re_detail_106200::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)':
bitmap.cc:(.text._ZN5boost16re_detail_10620016re_is_set_memberIPKccNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_S8_S8_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10620016re_is_set_memberIPKccNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_S8_S8_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0xee): undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
bitmap.cc:(.text._ZN5boost16re_detail_10620016re_is_set_memberIPKccNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_S8_S8_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10620016re_is_set_memberIPKccNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_S8_S8_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x2ce): undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
../libcolmap.a(misc.cc.o): In function `std::string* google::MakeCheckOpString<char, char>(char const&, char const&, char const*)':
misc.cc:(.text._ZN6google17MakeCheckOpStringIccEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIccEEPSsRKT_RKT0_PKc]+0x4f): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../libcolmap.a(option_manager.cc.o): In function `colmap::OptionManager::Parse(int, char**)':
option_manager.cc:(.text+0xe16d): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
../libcolmap.a(option_manager.cc.o): In function `boost::program_options::basic_parsed_options<char> boost::program_options::parse_command_line<char>(int, char const* const*, boost::program_options::options_description const&, int, boost::function1<std::pair<std::string, std::string>, std::string const&>)':
option_manager.cc:(.text._ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE[_ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE]+0x1b8): undefined reference to `boost::program_options::to_internal(std::string const&)'
option_manager.cc:(.text._ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE[_ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE]+0x287): undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
option_manager.cc:(.text._ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE[_ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE]+0x3fc): undefined reference to `boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
../libcolmap.a(pose.cc.o): In function `std::string* google::MakeCheckOpString<int, ceres::DimensionType>(int const&, ceres::DimensionType const&, char const*)':
pose.cc:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
collect2: error: ld returned 1 exit status
src/exe/CMakeFiles/colmap_exe.dir/build.make:139: recipe for target 'src/exe/colmap' failed
make[2]: *** [src/exe/colmap] Error 1
CMakeFiles/Makefile2:1184: recipe for target 'src/exe/CMakeFiles/colmap_exe.dir/all' failed
make[1]: *** [src/exe/CMakeFiles/colmap_exe.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

OK,, let's modify NVIDIA headers (`host_config.h` or something like that) so that it would allow to build with stock GCC 7.2. Now, compiling `colmap` gives error:
```
error: identifier "nullptr" is undefined
```
It seems that `NVCC` has to be enabled to use C++11? Added cmake argument for that:
```
-DCUDA_NVCC_FLAGS='-std=c++11`
```
But now there's yet another error:
```
/usr/include/math_functions.h(8897): error: cannot overload functions distinguished by return type alone

/usr/include/math_functions.h(8901): error: cannot overload functions distinguished by return type alone

2 errors detected in the compilation of "/tmp/tmpxft_00012575_00000000-7_ProgramCU.cpp1.ii".
CMake Error at pba_generated_ProgramCU.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/tomas/opensource/colmap/build/lib/PBA/CMakeFiles/pba.dir//./pba_generated_ProgramCU.cu.o`
```
Googling around I've found suggestion to add `-Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO` options, but it doesn't seem to help...

I've also tried to build `colmap` with GCC 5.4.1, if NVIDIA requires so, but that gives another set off errors, like:
```
/home/user/opensource/colmap/lib/PBA/SparseBundleCPU.cpp: In member function ‘int pba::SparseBundleCPU<Float>::SolveNormalEquationPCGX(float)’:
/home/user/opensource/colmap/lib/PBA/SparseBundleCPU.cpp:3487:8: error: ‘__builtin_isfinite’ is not a member of ‘std’
   if (!std::isfinite(alpha0)) {

```

Please.. help :)

[0] https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1710 
[1] https://stackoverflow.com/a/48402248

**Comment by ahojnnes** [comment]
I guess, the easiest option would be to downgrade CUDA. In general, it is a bad idea to use the latest CUDA version in my experience, since it is usually full of bugs and problems. Otherwise, I don't quite know how to help with your specific problem.

**Comment by Talkless** [comment]
For me It seems that Cuda does not support newer than GCC 5, meanwhile Colmap needs more recent GCC due to missing C++11 features such as std::isinfinite(), etc? it's kinda.. a non-match :) .

Not sure why older Cuda should support newer GCC..?

**Comment by ahojnnes** [comment]
I am using CUDA 8 and GCC 5.4 on Ubuntu 16.04, so I am not sure what the issue is on your system?

**Comment by Talkless** [comment]
Strange, With 5.4 I've got that:
```
/home/user/opensource/colmap/lib/PBA/SparseBundleCPU.cpp: In member function ‘int pba::SparseBundleCPU<Float>::SolveNormalEquationPCGX(float)’:
/home/user/opensource/colmap/lib/PBA/SparseBundleCPU.cpp:3487:8: error: ‘__builtin_isfinite’ is not a member of ‘std’
   if (!std::isfinite(alpha0)) {

```
Anyway, will try compile with Cuda 8 if friend will want to try again with Colmap (I'm not user myself).

**Comment by ahojnnes** [comment]
Please checkout the latest commit on the dev branch. This should fix your issues. I tested it and it works with the default CUDA and GCC versions under Ubuntu. You might have to recompile Ceres-Solver.

**Comment by Talkless** [comment]
Cool, thanks, most probably gonna try this weekend.

**Comment by Powerbyte7** [comment]
I had the exact same issue yesterday and i found [this](https://github.com/ethereum-mining/ethminer/issues/731) thread
Someone suggested to use these commands

`sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10`
`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10`

This solved the problem for me

**Comment by ahojnnes** [comment]
Thanks for letting us know, this will hopefully be helpful for other people as well.

**Comment by Talkless** [comment]
Thank you @Powerbyte7 , I might try that this weekend.

**Comment by Talkless** [comment]
I managed to build colmap on 17.10 by installing Cuda 9.0 from NVIDIA website, and selecting GCC-6 as @Powerbyte7 suggested.

Main issue was that default Cuda 8 on 17.10 could not be used with GCC >5 (it's 7 by default), and colmap could not be built with GCC = 5 :) .
